[
  {
    company: null,
    contact_email: "ramzanbhai@gmail.com",
    created_at: "2025-06-18T07:04:51-04:00",
    currency: "PKR",
    email: "ramzanbhai@gmail.com",
    financial_status: "paid",
    fulfillment_status: null,
    name: "#1016",
    phone: "+923055035360",
    customer: {
      email: "ramzanbhai@gmail.com",
      created_at: "2025-03-03T17:26:50-05:00",
      updated_at: "2025-06-18T07:04:52-04:00",
      first_name: "ramzan",
      last_name: "bhai",
      note: null,
      phone: "+923055035360",
      default_address: {
        customer_id: 7940192698594,
        first_name: "ramzan",
        last_name: "bhai",
        company: "shopilam",
        address1: "D Ground",
        address2: "workspace",
        city: "Faisalabad",
        province: null,
        country: "Pakistan",
        zip: "38000",
        phone: "+923211893255",
        name: "ramzan bhai",
        province_code: null,
        country_code: "PK",
        country_name: "Pakistan",
        default: true,
      },
    },
    fulfillments: [],
    shipping_address: {
      first_name: "ramzan",
      address1: "D Ground",
      phone: "+923211893255",
      city: "Faisalabad",
      zip: "38000",
      country: "Pakistan",
      last_name: "bhai",
      address2: "workspace",
      company: "shopilam",
      name: "ramzan bhai",
    },
  },
];

